### PR TITLE
Added developer-setup target to Makefile to install protoc

### PR DESCRIPTION
**Pull request by medyagh**
fixes https://github.com/campoy/justforfunc/issues/21

### CODE REVIEW

**Comment by medyagh** [comment]
I signed it!

**Comment by medyagh** [comment]
@campoy could I please get a +1 ?

**Comment by campoy** [comment]
this is quite an interesting change but I do not understand very well what's the reasoning behind it

This should work *only* for mac, right?
What about linux or windows? do you think you could add that too?

**Comment by medyagh** [comment]
@campoy true this is a first step to at least show that you need to install protoc and here is one for mac, someone can add a target for linux and windows also. I could add maybe in another PR if I setup a windows and linux VM. if thats okay with you.

**Comment by campoy** [comment]
I think I'd rather document this on the `README.md` and explain they should install `protoc` however they want, rather than hiding it in the `Makefile`.

Also, what if you don't use `brew`?

**Comment by medyagh** [comment]
fair enough :)

**Pull request closed without merging**
