### PR TITLE
Rename slightly confusing variable name

### PR DESCRIPTION
**Pull request by benjamin-thomas**
Hello @campoy 

A tiny nitpick, hope you don't mind. I found that part confusing/hard to read.

I think it's better to use another name rather than to override 2 lines below, with a complete different meaning.

### CODE REVIEW

**Comment by benjamin-thomas** [comment]
I signed it!

**Comment by campoy** [comment]
Hey, could you also change it in the other worker functions?

**Comment by benjamin-thomas** [comment]
Hello @campoy, the other worker functions don't have that ambiguity because `i` always represents the same thing (a row).

Skimming through the code, when seeing line 142, and directly focusing my attention on line 146, it automatically triggers a question in my brain "why wasn't that var passed around?".

image

That's the reason I thought this change could be useful.

In the other cases, you override that same variable due to the inline function, but that makes perfect sense to me.

**Comment by campoy** [comment]
I actually rewrote the post with the feedback on that PR so this name is not relevant anymore.
Thanks for the contribution, though!

**Comment by benjamin-thomas** [comment]
No problem, keep up the good work :)

**Pull request closed without merging**
